# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SourceDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SourceDemo

  target 'SourceDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SourceDemoUITests' do
    # Pods for testing
  end

end
